braid = {
    'n': 9,
    'p': 17,
    'l': 5
}
x = 'gANjc2FnZS5ncm91cHMuYnJhaWQKQnJhaWRHcm91cF9jbGFzcwpxAChYAgAAAHMwcQFYAgAAAHMxcQJYAgAAAHMycQNYAgAAAHMzcQRYAgAAAHM0cQVYAgAAAHM1cQZYAgAAAHM2cQdYAgAAAHM3cQh0cQmFcQpScQsoY3NhZ2UucmluZ3MuaW50ZWdlcgptYWtlX2ludGVnZXIKcQxYAQAAADFxDYVxDlJxD2gMWAEAAAAzcRCFcRFScRJoDFgBAAAAMnEThXEUUnEVaAxYAgAAAC0xcRaFcRdScRh0cRmFcRpScRsu'
threshold = 8
p = 405762563